apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:HJ072glPNk/NPgOgPPEAfAf6helFyvwaWsCkLYZeYqhZ0mVi1KXP6smzTJI9Wu/bNoyRgqZlHVIC7q4k+edesq4Q/nwNXJfb/x2Gx+PczO42HN+8jXqtARN0855a3SLkkbHs8xyQ/mfExEmBrIhIM6b8Kdu/inBt+1g4XCljaKDHVV3oQW7+QB16ozWstKIHEFOF1iVD8k3taSLlMSLYXt5F2yU84wDObc8PipjlVw42WPkEzlPF/XsKZGfuFcQTeSF5WI2H+V07wzmSmAP+ZzD1Gpazfx/TBeVhNdig8dxN59OFCIfBqdmAgRMHUqrV7xLyTHN7up4PkyxZhq/nSaGPWxc=,iv:cck8iaQGc26mJfzZwZYQU9YVauFdh3JmYkS2G30I0Ok=,tag:sexIFVIyERg81aZ2z+0ifw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1mxhc9wjkk9dhhx3jwee9yr5jltjddzqwye0rp6qv8yk7d3pukdzs6qgfyk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN0pzWmRZM3FWTGVadmhU
            Y2IzTnY4TFNXOGdDQkpxa3FiRTNKVWsrbUI4CjZnZ2RFZFo3SVZ2TGV1YTZCaDlU
            V0IxSkhWbGhUM21PNEd0TmFrWFFYR0kKLS0tIEZTdGVkMUVCVUhseVFubk55Nk9B
            TURwVThHeHY2Rlp1VTN4dmVKRWdvZm8KzErhTYHsd1h9FD+AsmZwKcQeSk1hRnjf
            +7OTKWXE8IotAFnvWHub2Ht9Tck7DTWLk18sA6KXJFMNR9eVkwGBvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T13:13:24Z"
    mac: ENC[AES256_GCM,data:akJ5y39bGUMynP5FQsBhgfgNbCEvdcjHMtoQlUDMMlEUJATftzRBb3b1yyG4n+9GzGnHheZ9ccShicPhkhW0MSgt2KgMpA8SLQ2FR5jvv+Mu7gr3V6CO85XZ8nYfYJtsHbxLibKvCsLlWPVty1ihp661H1pw73ifEVmC6rGHeho=,iv:wQQfsQvR78Eqcc9cWxv8yIrWEZi8vZPsD8vn64a0Wn4=,tag:gYEM/zKyw5DfhnMo1q6scQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
