apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:ohwIwcM6a/ajcm7n/5e0RHjqIGbYkjo9sK1A63YYQyskZFAl/fmo4FOptgIjuHtcQta7M0uOxnZHrjK/+CgCL8/UzhNhmLC8NYmh87FdUsLk9KFVxdPlmzPac9vMHwbjGpDwM/gcx9ScXXNhhNOkrr5KF1ZDvWxzRKyNnQg0t9Fvl7JZ+Aqhcyd7MW+0MaY5wXdywV0vPwjPXIp5xXkG9F1Bjbio34tpEsGcXfSxzxD0yo8uc97eD0l5HpKvL/cgxDOz4HXiw7RS/cLXu7/O2QGbmJ1Nfsc5vIO6UNRLO9ugaIrwZ/vKJbAcA5nAw5fKCyk2FNvNhClTNJwIq5t9hAUMxLc=,iv:WYO5XUQwY81BoiouZTX28AXGpJO4fU2QrdbaYZmNluA=,tag:wEiubx3ub9ppi2tS4Y/Nqw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1mxhc9wjkk9dhhx3jwee9yr5jltjddzqwye0rp6qv8yk7d3pukdzs6qgfyk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUVB0R1grRzFuS3lWSS9h
            aURwVWt4VllzYmNpd2NocHFFNXFPbWV6M1hvClNZUGYyd1MxQ1RQNll2NkhUMkRL
            OElaR3BzR0F4cDBLclU0aU1EYXo0TGsKLS0tIDJZNmJRQXQvL1g2eUd3Tng2VGky
            aWxDakpaMmFwMk53cmp2NTk5blhMczQKmgti++4+ofXrq5XL71ZFhTvN50sT3OQv
            fso0nPfAVE4JDsY4h+j5PLHKxv56reGcmpJpVgv8t5TUPAMGI3z2NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T11:00:45Z"
    mac: ENC[AES256_GCM,data:zPq6NKvj71YUXZTuEfgK06g1+0sDGDaTFrtUpfrcbA8sjdZgtupVFINdtn/u+6rjyg/jOiSLs516fNBjCD7nl6ZqHGPwkKmyQpbvZUWyzbuA+RiLtKIEgpiULTquu31gbUPjSCDuCnmXEAoDDqwBmvm7rtJy/lX+ya9q9tsuTtE=,iv:Rwa9Fge/dDw5xla7mk0iiputpSwJr6L9ZX9HQmfxpNk=,tag:7UwbjBdkdQGGCcWPl1zz0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
