apiVersion: v1
data:
    credentials.joson: ENC[AES256_GCM,data:mLGdyF5p7gT86/WktNIOg3mZQql3XEh6m5jaESritfD+fGP9/TJ5DbwPYbb3eHFF2ilTwcLw2Ho4WiCCDiBxx9M8mvKi+DyNe5MFX+GtYJ4QW30o8R37k+oGK3LBeu+SNYoZtTzDN8WaVcqGBRYvIyJ5OiyOgZ31jzp/Pup/uVAAP0Ic6nsM/dhWQL7VR6SgEBKErp1uKtXDFLDPDfYjPGf7U0T+Jmy1QnBfa0CjjGtdU9c1lTl1pVb7PKfDZAXSfg12BNNAEkhHq20/BedR2w7Of8X+7X3b44QXdER21znVexf0wPm2199QAgiYB8Ng0WjxxdHi9A8olgx9jQ44+ZCdHOs=,iv:niEh+Mc7Vq6fGksNNA6rG1/sjPC4E4Xil9YhZg6qU1w=,tag:/lJ4XNAFsKqgnwX4CrM63A==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1mxhc9wjkk9dhhx3jwee9yr5jltjddzqwye0rp6qv8yk7d3pukdzs6qgfyk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYldyQ3l1SDdlSGVLNXpP
            R1pWMG4xc3B6aHBIOFdnWXlTVHhJRWw0RXhFCkRHTnc4ZkRCKy9OM2ZBSXA0b3Yv
            ZzQzTVRKdzltUWt3TDN3RDBhZURjWjgKLS0tIDQzYm1hT3lYRmpvWHQ1dUwwZmVZ
            aUhBMXFwRVBlRDN4T3NOSWk2cGZuemcKDwP6pGCgAQLc54B1NgQukhOiOetd2RC2
            INFstk8y6qoFc6CMtLOaeTrB5VmGOZF0NNxn8RN7J/r3QsPGpeq91A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T17:41:30Z"
    mac: ENC[AES256_GCM,data:lxGAiXvaU3jwJ8y05rbtpcsPbwRk7JPV02LzVvDXIK47TceyvJUnTFG9I5KjqBYEXeib4ZSDEfMvBeg3lTotwjCxKvS9NF8KBQtc0Lw+HmK4yNFWeAPeWw+euoQEWYi1zMTOiNtcatyFHwJYJ8kEUYtzIf0VuWgfrI6XHcDbAG8=,iv:0A1l9bF/nXNVioa6qZntmZIbPlrYv0fFcPhNZ2iA/Fo=,tag:CV3d5qo2UuA37tWUq3YHGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
