apiVersion: v1
data:
    12e7f937-ec3d-4fc4-872c-7a2bcc916623.json: ENC[AES256_GCM,data:WIF2L37En0Ey2PP06WrBnidsb7vVFNbVIu4WWUyT9mqXxw7PHu/XjItec9ctU+lXLNTbVV+yntfeels1FzOuATb3Z7eDPF8K+pWi/lw5VhS3jlIDCCxg2HPZl6CZCHjxlqOT9CY3wCoOcGQymgmdwcn/kuiypLpIypsFUT87lbkbXjjCc03mGlxZPrQ8s5J13OGoKkuXCyg2nDPGxV00Iwi7uxSmkWr9bZcibMMkWjvF0j6sgpdrHaJrHM5vklj+Xyqo4GHFRkhbZmOt4MSvMt065mu2f8FNPERj5c9uxZrNRnwhdEQsiSHYWWKuosRLwyWFhx02JF+ODdedH6mZUsLu0+Y=,iv:ezSbqR0yGt2q6CRUbOF6Ws+6Xzf2yxxS3EOU+m2NEHA=,tag:+EPjCn1AJK/vjbamcKSmow==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1mxhc9wjkk9dhhx3jwee9yr5jltjddzqwye0rp6qv8yk7d3pukdzs6qgfyk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDc09lZVpoeHhhaWtsYXhs
            SHBkVWRZVEdOZzRDZzB3WGFnU0l5NWk4aUNNCkFobXA5T0M3VHcwWHNLT0tRV1Vz
            bmdualpxL2dQWlJJY2ZZMHR6QVRjSjQKLS0tIGRuSUtoVDB0a0paSEd1Q1JHUTNQ
            S3pDZVJQSmZ1Y1UwRGswdzlZZ1plVTQKJp7OGoiEwVAG7eNsX4oOe5nvoV7QsYFO
            GC/ZlK6dI2WdkdItjm0A+5qaZTyGEIkgWo1WUgBKb+NtgyE1eFsNig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T20:10:50Z"
    mac: ENC[AES256_GCM,data:JBuFDvMjy7ayRsBUGwimxgiUb+IaOq9PZVnV04/hZcZ8mWVA5+wDWVmc8LkS5xGYhAWkC/KNZ6iAa4P8ZJ7Uwkq5W9nKUmUXxx185xyPa6MJPSRai8k+yI7yxKKlvGsIeGS/ovymEMZAObvlE716q9veciPRkH+sVLm/IBEPDPQ=,iv:NpFPndxktlT1rzZu8soJW3swJZMGtMpOyfrPemPUbbI=,tag:hOo0aF97xxDVps40Uohr5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
