apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:Zy7101ueKX8a+tYr7PBXxxNQuwrW6+etg5TYFtf0HzNIoDQjqbXmCJFoiIqqS+SiMQGDMgXpb+tTJtOCPyOfqmdd7DPIV8IjBhwHMY/wh2uSC04E75sKJkXMPf4yELSHWJUb38uO5xjZuvYkErcdYCHsVG7x8X10BJkgW2OI8PnPiyV+Hml/kX8DZr35G8u9tQOMCpiC7vv0D5l1S/jsdalIxdlcbwx6iU7U1mRkp+Y1VTlFz2dvkCyNOHMdYToIaK7Dp46itCwZFruK4lkBlY8reW1taUTNBiLklLAq2XVROfsrM7t3AjsYXe93ZIRYUdiUlGxZBmS5NeGBwEjY8igdkJI=,iv:tfkrABIN9/nnT+3gi7EXAYD4nQ4Sq/cwi0KBerEbncM=,tag:9qzg0Q94/SOM5iiGiV335A==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1mxhc9wjkk9dhhx3jwee9yr5jltjddzqwye0rp6qv8yk7d3pukdzs6qgfyk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTHdXQkJ1OE9GSnZWUkZP
            Z2N2VlhnMkZLY3VVQzhwR1RQWEE5S0V4MGlZClk1UktjcWRHVHhtRmdhZFhiN08w
            akhTOUd3aS9YZmoyZUREaEF6bkh3SlkKLS0tIEVycEtWODZ2YzNqMU5ucitmbjZW
            YVpsRmZmVzBsRWRvazBaME1JdmVRbHMK4FkLyM2d0Uj4ZoPd2X2+eSCOW1xCMWsF
            FGGcx7+qkqd20jYR4lbkd9Rpng20jk2pR35KvfMPM08vI5aL2m24SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T18:44:32Z"
    mac: ENC[AES256_GCM,data:85x47JDCseg1SLwP+0WiLXUH/W19YdvhpbhImJ/vV/DOEmaY8mQ2JNTgf688cmEM4P5f+hPXtqViPvvJg8e//3bFXzK8kfNeiVhM5A1tJmWyrzEWUMZt+GpuaCpOM7fyEgcjvWtwxnhBNIaPBrbdvbsLIw58UacWuMif+22FtlQ=,iv:1xG9wfImI5NcA5qWRdk8tXUBXntkblKhpv3df/AfW8U=,tag:rLOHnLpROSpWdBBhe/bctQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
