apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:WMjFaH7IHNo=,iv:mfMeKTujlUW9MSOdVmad4EeuKRQzefbHzc0uuoDLBZo=,tag:G7FhcNS+P8ecpVQtkjz6kw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:7dzqx2B5W/HoE4bSvsTGlg==,iv:PLUWphdurPGE2n3FAsYkAHwVif/P5ywGy1m6CGKNgmU=,tag:yFm5yP6sULa4EB2E/vLt3A==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age1mxhc9wjkk9dhhx3jwee9yr5jltjddzqwye0rp6qv8yk7d3pukdzs6qgfyk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYTAzK2w1eWJ2VXlaZ3RU
            Q1IzbDAvVUxhc0dMaFRKZWJCUit0WEtwY2t3CjQzMXlsdkRRWXd2QWIzeTFoNHZL
            bERnN09IMjd1L0pTaUlUVi9ZNFBBSTAKLS0tIFNkNnhoWTMrajd3UXkrMXNFeDRB
            ZlpNUWV0RVQ3U2ZpV1BpalhONE1teW8Ko9Ij7Cxr1GQ0Lbgfh54ta/xoSHwxS6j4
            VMULUy/2nWm1l6DEJ+IDIO9282R1exvyWnjDOv22Bun/3XCDcjfE+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T16:50:32Z"
    mac: ENC[AES256_GCM,data:1GJV+ta2hNgSgPOeJveZFFeeH8L3Bp+v/7bEHW7DM91L9T/A2zXNK/L3TOvh2SSo2vPV0aPi7bWtOW+NEwt9+Ret90stqly7kWMwrxAsiJUchsFfciZfDSvZcT/scpofrGBvP1QgGJhgf6IcduqB9/keLuOmMBRUTRsRXglGYZU=,iv:BLK1r4LYrQvIqBhX76bDAUR1cSoXIW8Z69NUO4LMOC0=,tag:4kCkIjcw3Ionr77gV6iEeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
