apiVersion: v1
data:
    password: ENC[AES256_GCM,data:cwwqgf5pnfg=,iv:r6djAl6snKyegiCB2cvmfzQ+AW0sprTW8Vn5TXLwPbs=,tag:cTCABRIo5CRSmY/z05zQ4g==,type:str]
    user: ENC[AES256_GCM,data:I5w0lzN0L+8=,iv:5LZ+RX1JSDE384MSg4MtblxjKBnDN6DmVK40u6lCNw4=,tag:uf4CWPTYhQfdw+avjtvLdQ==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age1mxhc9wjkk9dhhx3jwee9yr5jltjddzqwye0rp6qv8yk7d3pukdzs6qgfyk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM1ZQSHN1bDk5aGNzSHN4
            SUw0ZXRqYVVuYlQ2UmpKdDJoOHVlaHdUMnc4Cnk4RzhKYWc4bThIZTM2MEZ5V0hR
            Y3YzaUpFbGx3NU5LQUorOGNremdSQlkKLS0tIHR2Q0tTVmtLdjhHZGN4bXk2THFR
            cGFYMEJ2end6UytkT3RLbncvaHBVREkKgr9ef0KO25GYL+2YRJ6a/ZSFH1s5PISt
            1dgCJthinCsv3JnZTZjbyq4Ja+YlCaYu3wtf4oF6Jv1Kqsj85rwHhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T19:38:27Z"
    mac: ENC[AES256_GCM,data:FcQpqTJ1ztXEZxvMzgiz4cD/X2ANXTuq7SOc0ipUp9/4eTkpGHmOUZSYmHlxz2Vll8+4zM0M5rzkAyIKHJFC/N1LetCgZBF0rnvoSqRkpSPgGhpEzYonFnmfD8RPQahPxKWUISkKY9I4DxmMgu0lwnp11qeTlx6IcnDkrvZnt6k=,iv:xD7rMTQjgvzVdRv/rjeOiR1ij/BkGKtp+GETu95uIMA=,tag:B3kEfU9rJXKbITCQRM2AIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
